### ISSUE TITLE
On-screen keyboard

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/armenian-mss#1]
There are two keyboard layouts for Armenian: Western and Eastern. No other languages are required.

**Comment by andrew-morrison** [comment]
There is a tiny amount of Greek, so that keyboard might be worth keeping.

**Comment by IgnatG** [comment]
//done

**Comment by andrew-morrison** [comment]
So, are there no Armenian keyboards available?

If so, there is no point having Greek and no Armenian.

**Comment by IgnatG** [comment]
nop. no keyboard for Armenian. I can't find the unicode characters for it either. I'll take it out in that case

**Comment by IgnatG** [comment]
//sorted - I took it out
