### ISSUE TITLE
new user access request

### ISSUE THREAD

**Issue by rbnmyr** [bodleian/armenian-mss#6]
Armenian specialist @ Uni of Oxford; entered the original data for this catalogue. Now working with David Zakarian on updating the material.
Thanks!

**Comment by ahankinson** [comment]
Hello! Could you please add your name and e-mail address (preferably your `@ox.ac.uk` one) to your GitHub account so we can track who has access to this catalogue? Thanks!

**Comment by rbnmyr** [comment]
Thanks for this, and apologies for the oversight. Should now be done.
All best,
Robin
