### ISSUE TITLE
New user access request

### ISSUE THREAD

**Issue by Archpoet** [bodleian/armenian-mss#7]
I am David Zakarian, scholar in the Armenian studies at the University of Oxford, and I will be updating the existing catalogue alongside Robin Meyer.
Thank you!

**Comment by ahankinson** [comment]
Hello, could you both please e-mail me (andrew.hankinson@bodleian.ox.ac.uk) and CC Gillian Evison so that I know that this is an endorsed effort? Thanks.

Could you please also add your name and `@ox.ac.uk` e-mail address to your GitHub profile so we can keep track of access?
